let suggestions = [
    "Harry Potter | FR",
    "Supercondriaque | FR",
    "Dark Phoenix | FR",
    "Astérix et Obélix : Mission Cléopâtre | FR",
    "Demon Slayer: Le train de l'Infini | FR",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
